project
dmngoodcoffee/loyalty-system-service pull request #1
Opened 2022-06-04 14:21 UTC by mkarulina

2022-06-15 19:41 UTC, lugingf requested changes
В общем работа очень хорошая. Код приятно читается и понятно что где происходит. Оставил комментарии, некоторые просто вкусовщина, некоторые считаю критичными, поэтому  предлагаю поправить

2022-06-15 19:41 UTC, lugingf commented on cmd/gophermart/main.go
> +func gzipHandle(next http.Handler) http.Handler {
Я бы это к мидлварам закинул

2022-06-15 19:41 UTC, lugingf commented on cmd/gophermart/main.go
> +func auth(next http.Handler) http.Handler {
И это туда же

2022-06-15 19:41 UTC, lugingf commented on cmd/gophermart/main.go
> +func tokenHandle(next http.Handler) http.Handler {
и это кажется тоже мидлвара

2022-06-15 19:41 UTC, lugingf commented on internal/accrual/cron.go
> +	c := cron.New()
❤️

2022-06-15 19:41 UTC, lugingf commented on internal/accrual/cron.go
> +	s := storage.New()
Каждый раз реинициализируем сторадж? Может это вынести из функции?

2022-06-15 19:41 UTC, lugingf commented on internal/storage/storage.go
> +	GetUserLoginByToken(token string, db *sql.DB) (string, error)
Я бы то, что касается регистрации/аутентификации пользователя не стал бы под один интерфейс заводить. Сделал бы ему отдельный

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_history.go
> +			"CREATE TABLE IF NOT EXISTS withdrawals_history ("+
Ой, а давай миграции унесем куда-нибудь отдельно и не будем каждый раз их дергать при обращении к БД?

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_history.go
> +			"INSERT INTO withdrawals_history (user_id, order_number, sum, processed_at) VALUES ($1, $2, $3, $4)",
Вообще есть негласное правило, что на каждую таблицу - свой Storage. Особенно если джойнов нет. Тогда и не будет странно смотреться разбиение методов одной структуры по разным файлам

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_history.go
> +	go doIncrement()
А зачем мы это в горутину, если сразу же стоим и ждем ее?

2022-06-15 19:41 UTC, lugingf commented on internal/accrual/cron.go
> +	orders, err := s.GetAllOrders()
Ммм, а точно нам каждый раз нужны именно все заказы? Даже те, которые уже обсчитаны?

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_orders.go
> +			"CREATE TABLE IF NOT EXISTS orders ("+
Давай везде миграции вынесем отдельно. Пусть они раз дергаются при старте сервиса и все

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_orders.go
> +	go doIncrement()
Тут такой же вопрос. Зачем нам тут одна горутина, которую мы точно так же как и любой другой синхронный код ждем?

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_orders.go
> +	db, err := sql.Open("pgx", dbAddress)
А зачем каждый раз иницировать коннект к БД? Давай это сделаем один раз, объект полученный положим в Storage в свойство и потом просто будем каждый раз им пользоваться

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_orders.go
> +		existinпOrder, err := db.ExecContext(ctx, "SELECT * FROM orders WHERE number = $1", order)
Тут, кажется, какая-то опечатка с кирилицей

2022-06-15 19:41 UTC, lugingf commented on internal/storage/db_orders.go
> +	db, err := sql.Open("pgx", dbAddress)
и тут и везде - давай один раз законнектимся и потом переиспользуем

2022-06-24 06:20 UTC, mkarulina commented on cmd/gophermart/main.go
> +func gzipHandle(next http.Handler) http.Handler {
Спасибо, комментарии очень полезные)
Вроде бы всё поправила. Единственное, мидлвары вынесла в отдельный интерфейс просто -  правильно поняла? Или тут тоже есть какие-то правила по структуре и нужно сделать как-то по-другому?

2022-06-24 13:22 UTC, lugingf commented on cmd/gophermart/main.go
> +func gzipHandle(next http.Handler) http.Handler {
Сорри, я продолбал коммент. Не в интерфейс, просто в другой пакет. Им отдельный интерфейс не нужен, они и так реализуют какой-то стандартный из httpшных (забыл какой)

2022-06-24 13:29 UTC, lugingf approved these changes
Принято, спасибо за работу! :)

2022-06-24 15:29 UTC, merged